### PR TITLE
update to compile with conduit-combinators >= 1.1

### LINKED ISSUE #1: Does not build with lts-8.14
I've tried building udp-conduit with lts-8.14 and it fails with the following error:

```

    Configuring udp-conduit-0.1.0.4...
    Building udp-conduit-0.1.0.4...
    Preprocessing library udp-conduit-0.1.0.4...
    [1 of 1] Compiling Conduit.UDP      ( src/Conduit/UDP.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Conduit/UDP.o )
    
    /tmp/stack8661/udp-conduit-0.1.0.4/src/Conduit/UDP.hs:56:5: error:
        • Couldn't match type ‘a’
                         with ‘bytestring-0.10.8.1:Data.ByteString.Internal.ByteString’
          ‘a’ is a rigid type variable bound by
            the type signature for:
              udpSink :: forall (m :: * -> *) a o.
                         (MonadResource m, IOData a) =>
                         String -> PortNumber -> ConduitM a o m ()
            at src/Conduit/UDP.hs:51:8
          Expected type: ConduitM a o m ()
            Actual type: ConduitM
                           bytestring-0.10.8.1:Data.ByteString.Internal.ByteString o m ()
        • In the expression: sinkIOHandle (udpHandle host port SinkSocket)
          In an equation for ‘udpSink’:
              udpSink host port = sinkIOHandle (udpHandle host port SinkSocket)
        • Relevant bindings include
            udpSink :: String -> PortNumber -> ConduitM a o m ()
              (bound at src/Conduit/UDP.hs:55:1)
    
    /tmp/stack8661/udp-conduit-0.1.0.4/src/Conduit/UDP.hs:69:5: error:
        • Couldn't match type ‘a’
                         with ‘bytestring-0.10.8.1:Data.ByteString.Internal.ByteString’
          ‘a’ is a rigid type variable bound by
            the type signature for:
              udpSource :: forall (m :: * -> *) a i.
                           (MonadResource m, IOData a, MonoFoldable a) =>
                           String -> PortNumber -> ConduitM i a m ()
            at src/Conduit/UDP.hs:64:8
          Expected type: ConduitM i a m ()
            Actual type: ConduitM
                           i bytestring-0.10.8.1:Data.ByteString.Internal.ByteString m ()
        • In the expression:
            sourceIOHandle (udpHandle host port SourceSocket)
          In an equation for ‘udpSource’:
              udpSource host port
                = sourceIOHandle (udpHandle host port SourceSocket)
        • Relevant bindings include
            udpSource :: String -> PortNumber -> ConduitM i a m ()
              (bound at src/Conduit/UDP.hs:68:1)

```

### PR DESCRIPTION
**Pull request by mihaigiurgeanu**
Fixes #1

### CODE REVIEW

**Comment by kqr** [comment]
Yes, that was an easy merge. Thank you. :)

Sorry for taking so long to respond.
