### ISSUE TITLE
Does not build with lts-8.14

### ISSUE THREAD

**Issue by joehealy** [kqr/udp-conduit#1]
I've tried building udp-conduit with lts-8.14 and it fails with the following error:

```

    Configuring udp-conduit-0.1.0.4...
    Building udp-conduit-0.1.0.4...
    Preprocessing library udp-conduit-0.1.0.4...
    [1 of 1] Compiling Conduit.UDP      ( src/Conduit/UDP.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Conduit/UDP.o )
    
    /tmp/stack8661/udp-conduit-0.1.0.4/src/Conduit/UDP.hs:56:5: error:
        • Couldn't match type ‘a’
                         with ‘bytestring-0.10.8.1:Data.ByteString.Internal.ByteString’
          ‘a’ is a rigid type variable bound by
            the type signature for:
              udpSink :: forall (m :: * -> *) a o.
                         (MonadResource m, IOData a) =>
                         String -> PortNumber -> ConduitM a o m ()
            at src/Conduit/UDP.hs:51:8
          Expected type: ConduitM a o m ()
            Actual type: ConduitM
                           bytestring-0.10.8.1:Data.ByteString.Internal.ByteString o m ()
        • In the expression: sinkIOHandle (udpHandle host port SinkSocket)
          In an equation for ‘udpSink’:
              udpSink host port = sinkIOHandle (udpHandle host port SinkSocket)
        • Relevant bindings include
            udpSink :: String -> PortNumber -> ConduitM a o m ()
              (bound at src/Conduit/UDP.hs:55:1)
    
    /tmp/stack8661/udp-conduit-0.1.0.4/src/Conduit/UDP.hs:69:5: error:
        • Couldn't match type ‘a’
                         with ‘bytestring-0.10.8.1:Data.ByteString.Internal.ByteString’
          ‘a’ is a rigid type variable bound by
            the type signature for:
              udpSource :: forall (m :: * -> *) a i.
                           (MonadResource m, IOData a, MonoFoldable a) =>
                           String -> PortNumber -> ConduitM i a m ()
            at src/Conduit/UDP.hs:64:8
          Expected type: ConduitM i a m ()
            Actual type: ConduitM
                           i bytestring-0.10.8.1:Data.ByteString.Internal.ByteString m ()
        • In the expression:
            sourceIOHandle (udpHandle host port SourceSocket)
          In an equation for ‘udpSource’:
              udpSource host port
                = sourceIOHandle (udpHandle host port SourceSocket)
        • Relevant bindings include
            udpSource :: String -> PortNumber -> ConduitM i a m ()
              (bound at src/Conduit/UDP.hs:68:1)

```

**Comment by joehealy** [comment]
The following changes make it build, but I suspect that is not the "proper" fix:
```
[joe@jx250:~/builds/udp-conduit/src/Conduit]$ git diff
diff --git a/src/Conduit/UDP.hs b/src/Conduit/UDP.hs
index 131fe19..2fcefaf 100644
--- a/src/Conduit/UDP.hs
+++ b/src/Conduit/UDP.hs
@@ -20,6 +20,7 @@ import Conduit
     , sinkIOHandle
     , sourceIOHandle
     )
+import qualified Data.ByteString as B
 
 -- | A type to distinguish when we want to read and write from sockets,
 -- simplifying the implementation
@@ -48,10 +49,10 @@ socketMode socketType =
 -- from upstream toward the destination. Must be used with
 -- 'Data.Conduit.runConduitRes', since it uses a finite resource (sockets)
 udpSink
-    :: (MonadResource m, IOData a)
+    :: (MonadResource m)
     => String -- ^ address to destination
     -> PortNumber -- ^ port number on destination
-    -> ConduitM a o m () -- ^ Can be viewed as a @'Data.Conduit.Sink' ByteString@
+    -> ConduitM B.ByteString a m () -- ^ Can be viewed as a @'Data.Conduit.Sink' ByteString@
 udpSink host port =
     sinkIOHandle (udpHandle host port SinkSocket)
 
@@ -61,10 +62,10 @@ udpSink host port =
 -- being sent to that interface and port. Must be used with
 -- 'Data.Conduit.runConduitRes', since it uses a finite resource (sockets)
 udpSource
-    :: (MonadResource m, IOData a, MonoFoldable a)
+    :: (MonadResource m)
     => String -- ^ address to bind to
     -> PortNumber -- ^ port number to bind to
-    -> ConduitM i a m () -- ^ Can be viewed as a @MonadIO m => 'Data.Conduit.Source' m ByteString@
+    -> ConduitM i B.ByteString m () -- ^ Can be viewed as a @MonadIO m => 'Data.Conduit.Source' m ByteString@
 udpSource host port =
     sourceIOHandle (udpHandle host port SourceSocket)
 
diff --git a/stack.yaml b/stack.yaml
index 16fdf78..20c7b32 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -1,7 +1,8 @@
 # For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
 
 # Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
-resolver: lts-7.2
+#resolver: lts-7.2
+resolver: lts-8.14
 
 # Local packages, usually specified by relative directory name
 packages:
@@ -30,3 +31,10 @@ extra-package-dbs: []
 # Extra directories used by stack for building
 # extra-include-dirs: [/path/to/dir]
 # extra-lib-dirs: [/path/to/dir]
+
+
+nix:
+  enable: true
+  pure: true
+  shell-file: shell.nix
+
diff --git a/udp-conduit.cabal b/udp-conduit.cabal
index a2210d5..a17a63e 100644
--- a/udp-conduit.cabal
+++ b/udp-conduit.cabal
@@ -24,6 +24,7 @@ library
                      , chunked-data
                      , network
                      , conduit-combinators
+                     , bytestring
   default-language:    Haskell2010
 
 source-repository head


```

**Comment by kqr** [comment]
It looks like you did exactly the right thing in your patch though! The "problem" is that in conduit-combinators 1.10 the I/O functions got specialised from IOData a to ByteString, so this library should be patched in accordance. (There were good reasons for that change to conduit-combinators, apparently. See [the changelog](https://hackage.haskell.org/package/conduit-combinators-1.1.1/changelog).)
